// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM5NQPXxTUFgQya6pBweVf7pcaHUtKkXg',
    appId: '1:1036143219493:web:ee732932ae99a1ccc8c0cc',
    messagingSenderId: '1036143219493',
    projectId: 'umrahtrack-hazz',
    authDomain: 'umrahtrack-hazz.firebaseapp.com',
    storageBucket: 'umrahtrack-hazz.firebasestorage.app',
    measurementId: 'G-TYY3DSGS8D',
    databaseURL: 'https://umrahtrack-hazz-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuE-EbABiRi21n45AbnVIZKzwmo1KupXE',
    appId: '1:1036143219493:android:f13c8594b7135a89c8c0cc',
    messagingSenderId: '1036143219493',
    projectId: 'umrahtrack-hazz',
    storageBucket: 'umrahtrack-hazz.firebasestorage.app',
    databaseURL: 'https://umrahtrack-hazz-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA94-3Y3he_Aco25BX_ZUdV4K2fkFSwK0Q',
    appId: '1:1036143219493:ios:cf5ae35ced3c583fc8c0cc',
    messagingSenderId: '1036143219493',
    projectId: 'umrahtrack-hazz',
    storageBucket: 'umrahtrack-hazz.firebasestorage.app',
    iosBundleId: 'com.example.umrahtrack',
    databaseURL: 'https://umrahtrack-hazz-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA94-3Y3he_Aco25BX_ZUdV4K2fkFSwK0Q',
    appId: '1:1036143219493:ios:cf5ae35ced3c583fc8c0cc',
    messagingSenderId: '1036143219493',
    projectId: 'umrahtrack-hazz',
    storageBucket: 'umrahtrack-hazz.firebasestorage.app',
    iosBundleId: 'com.example.umrahtrack',
    databaseURL: 'https://umrahtrack-hazz-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM5NQPXxTUFgQya6pBweVf7pcaHUtKkXg',
    appId: '1:1036143219493:web:3c5af6e2dbdebe94c8c0cc',
    messagingSenderId: '1036143219493',
    projectId: 'umrahtrack-hazz',
    authDomain: 'umrahtrack-hazz.firebaseapp.com',
    storageBucket: 'umrahtrack-hazz.firebasestorage.app',
    measurementId: 'G-HJKJLKMCP7',
    databaseURL: 'https://umrahtrack-hazz-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
